name: GPT-4o - Simple
description: No system prompt, no few-shot.
version: 1.0.0
components:
  api: openai
  model: gpt-4o
parameters:
  batch_processing:
    enabled: true  # set to false to disable batching
    batch_size: 32 # adjust this number to control concurrent tasks per batch
  temperature: 0
  system_message: ''
training_examples: []
created_at: '2026-06-21'
last_modified: '2026-06-21'
